import { FormEvent, useState } from "react";
import type { ChangeEvent } from "react";
type Dados = { nome: string; email: string; telefone: string; senha: string };
export function RegisterPage({ carregando, onVoltar, onCadastrar }: { carregando: boolean; onVoltar: () => void; onCadastrar: (dados: Dados) => Promise<void> }) {
  const [dados, setDados] = useState<Dados>({ nome: "", email: "", telefone: "", senha: "" }); const [erro, setErro] = useState("");
  const atualizar = (campo: keyof Dados) => (evento: ChangeEvent<HTMLInputElement>) => setDados({ ...dados, [campo]: evento.target.value });
  async function enviar(evento: FormEvent<HTMLFormElement>) { evento.preventDefault(); setErro(""); try { await onCadastrar(dados); } catch (error) { setErro(error instanceof Error ? error.message : "Não foi possível criar a conta."); } }
  return <div className="auth-screen"><button className="back" type="button" onClick={onVoltar}>← Voltar para entrar</button><div className="auth-heading"><h1>Criar sua conta</h1><p className="subtitle">É rápido. Vamos começar pelo básico.</p></div><form className="card" onSubmit={enviar}>{erro && <p className="alert error" role="alert">{erro}</p>}<label htmlFor="cadastro-nome">Nome completo *</label><input id="cadastro-nome" value={dados.nome} onChange={atualizar("nome")} required minLength={2} /><label htmlFor="cadastro-email">E-mail *</label><input id="cadastro-email" type="email" autoComplete="email" value={dados.email} onChange={atualizar("email")} required /><label htmlFor="cadastro-telefone">Telefone</label><input id="cadastro-telefone" type="tel" autoComplete="tel" value={dados.telefone} onChange={atualizar("telefone")} placeholder="(71) 99999-9999" /><label htmlFor="cadastro-senha">Senha *</label><input id="cadastro-senha" type="password" autoComplete="new-password" value={dados.senha} onChange={atualizar("senha")} required minLength={8} /><button className="btn btn-primary" type="submit" disabled={carregando}>{carregando ? "Criando conta..." : "Criar conta"}</button></form></div>;
}
