import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import App from "./App";

function resposta(corpo: unknown, status = 200): Response { return { ok: status >= 200 && status < 300, status, json: vi.fn().mockResolvedValue(corpo) } as unknown as Response; }
function preencherLogin() { fireEvent.change(screen.getByLabelText("E-mail"), { target: { value: "ana@example.com" } }); fireEvent.change(screen.getByLabelText("Senha"), { target: { value: "senha-segura" } }); fireEvent.click(screen.getByRole("button", { name: "Entrar" })); }
function preencherCadastro() { fireEvent.change(screen.getByLabelText("Nome completo *"), { target: { value: "Ana Souza" } }); fireEvent.change(screen.getByLabelText("E-mail *"), { target: { value: "ana@example.com" } }); fireEvent.change(screen.getByLabelText("Senha *"), { target: { value: "senha-segura" } }); fireEvent.click(screen.getByRole("button", { name: "Criar conta" })); }
function grupoCriado() { return { id: 1, nome: "Grupo dos Amigos", gestor_id: 1, valor_cota: "200.00", valor_premio: "2000.00", quantidade_participantes: 10, quantidade_ciclos: 10, data_inicio: "2026-10-01", status: "RASCUNHO", created_at: "2026-09-16T12:00:00" }; }
function preencherGrupo() { fireEvent.change(screen.getByLabelText("Nome do grupo *"), { target: { value: "Grupo dos Amigos" } }); fireEvent.change(screen.getByLabelText("Valor por ciclo (R$) *"), { target: { value: "200.00" } }); fireEvent.change(screen.getByLabelText("Quantidade de participantes *"), { target: { value: "10" } }); fireEvent.change(screen.getByLabelText("Data de início *"), { target: { value: "2026-10-01" } }); }
async function autenticarPelaSessao() {
  localStorage.setItem("toojunto_access_token", "token-valido");
  vi.mocked(fetch).mockResolvedValueOnce(resposta({ id: 1, nome: "Ana Souza", email: "ana@example.com", telefone: null }));
  const app = render(<App />);
  await screen.findByRole("heading", { name: "Olá, Ana Souza!" });
  return app;
}

describe("autenticação", () => {
  afterEach(() => { cleanup(); vi.unstubAllGlobals(); });
  beforeEach(() => { localStorage.clear(); vi.stubGlobal("fetch", vi.fn()); });
  it("renderiza a tela de login", async () => { render(<App />); expect(await screen.findByRole("heading", { name: "Bem-vindo ao TooJunto" })).toBeInTheDocument(); expect(screen.getByLabelText("E-mail")).toBeInTheDocument(); expect(screen.getByLabelText("Senha")).toBeInTheDocument(); });
  it("faz login e exibe a área autenticada", async () => { vi.mocked(fetch).mockResolvedValueOnce(resposta({ access_token: "token-valido", token_type: "bearer" })).mockResolvedValueOnce(resposta({ id: 1, nome: "Ana Souza", email: "ana@example.com", telefone: null })); render(<App />); preencherLogin(); expect(await screen.findByRole("heading", { name: "Olá, Ana Souza!" })).toBeInTheDocument(); expect(localStorage.getItem("toojunto_access_token")).toBe("token-valido"); });
  it("mostra erro para login inválido", async () => { vi.mocked(fetch).mockResolvedValueOnce(resposta({ detail: "E-mail ou senha inválidos." }, 401)); render(<App />); preencherLogin(); expect(await screen.findByRole("alert")).toHaveTextContent("E-mail ou senha inválidos."); expect(localStorage.getItem("toojunto_access_token")).toBeNull(); });
  it("cadastra e retorna para o login com confirmação", async () => { vi.mocked(fetch).mockResolvedValueOnce(resposta({ id: 1, nome: "Ana Souza", email: "ana@example.com", telefone: null }, 201)); render(<App />); fireEvent.click(await screen.findByRole("button", { name: "Criar minha conta" })); preencherCadastro(); expect(await screen.findByRole("status")).toHaveTextContent("Conta criada com sucesso"); expect(screen.getByRole("heading", { name: "Bem-vindo ao TooJunto" })).toBeInTheDocument(); });
  it("mostra erro de cadastro", async () => { vi.mocked(fetch).mockResolvedValueOnce(resposta({ detail: "E-mail já cadastrado." }, 409)); render(<App />); fireEvent.click(await screen.findByRole("button", { name: "Criar minha conta" })); preencherCadastro(); expect(await screen.findByRole("alert")).toHaveTextContent("E-mail já cadastrado."); });
  it("restaura acesso autenticado consultando /auth/me", async () => { localStorage.setItem("toojunto_access_token", "token-valido"); vi.mocked(fetch).mockResolvedValueOnce(resposta({ id: 1, nome: "Ana Souza", email: "ana@example.com", telefone: null })); render(<App />); expect(await screen.findByRole("heading", { name: "Olá, Ana Souza!" })).toBeInTheDocument(); });
  it("mantém login sem autenticação", async () => { render(<App />); expect(await screen.findByRole("heading", { name: "Bem-vindo ao TooJunto" })).toBeInTheDocument(); expect(screen.queryByText("Conta autenticada")).not.toBeInTheDocument(); });
  it("exibe a ação de sair para usuário autenticado", async () => { await autenticarPelaSessao(); expect(screen.getByRole("button", { name: "Sair" })).toBeInTheDocument(); });
  it("remove o token ao sair", async () => { await autenticarPelaSessao(); fireEvent.click(screen.getByRole("button", { name: "Sair" })); expect(localStorage.getItem("toojunto_access_token")).toBeNull(); });
  it("deixa de exibir dados da sessão ao sair", async () => { await autenticarPelaSessao(); fireEvent.click(screen.getByRole("button", { name: "Sair" })); expect(screen.queryByRole("heading", { name: "Olá, Ana Souza!" })).not.toBeInTheDocument(); expect(screen.queryByText("ana@example.com")).not.toBeInTheDocument(); });
  it("retorna para o login com feedback ao sair", async () => { await autenticarPelaSessao(); fireEvent.click(screen.getByRole("button", { name: "Sair" })); expect(await screen.findByRole("heading", { name: "Bem-vindo ao TooJunto" })).toBeInTheDocument(); expect(screen.getByRole("status")).toHaveTextContent("Você saiu da sua conta."); });
  it("exige novo login ao tentar acessar a área autenticada após sair", async () => {
    const { unmount } = await autenticarPelaSessao();
    fireEvent.click(screen.getByRole("button", { name: "Sair" }));
    unmount();

    render(<App />);

    expect(await screen.findByRole("heading", { name: "Bem-vindo ao TooJunto" })).toBeInTheDocument();
    expect(screen.queryByText("Conta autenticada")).not.toBeInTheDocument();
    expect(fetch).toHaveBeenCalledTimes(1);
  });
  it("usa Grupo na interface e permite iniciar a criação", async () => { await autenticarPelaSessao(); expect(screen.queryByText(/caixinha/i)).not.toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "+ Criar novo grupo" })); expect(screen.getByRole("heading", { name: "Criar grupo" })).toBeInTheDocument(); expect(screen.queryByText(/caixinha/i)).not.toBeInTheDocument(); });
  it("renderiza os campos e o novo rótulo de valor", async () => { await autenticarPelaSessao(); fireEvent.click(screen.getByRole("button", { name: "+ Criar novo grupo" })); expect(screen.getByLabelText("Nome do grupo *")).toBeInTheDocument(); expect(screen.getByLabelText("Valor por ciclo (R$) *")).toBeInTheDocument(); expect(screen.getByLabelText("Quantidade de participantes *")).toBeInTheDocument(); expect(screen.getByLabelText("Quantidade de ciclos")).toHaveAttribute("readonly"); expect(screen.getByLabelText("Data de início *")).toBeInTheDocument(); });
  it("calcula ciclos e valor do prêmio automaticamente", async () => { await autenticarPelaSessao(); fireEvent.click(screen.getByRole("button", { name: "+ Criar novo grupo" })); fireEvent.change(screen.getByLabelText("Valor por ciclo (R$) *"), { target: { value: "200.00" } }); fireEvent.change(screen.getByLabelText("Quantidade de participantes *"), { target: { value: "5" } }); expect(screen.getByLabelText("Quantidade de ciclos")).toHaveValue(5); expect(screen.getByText("R$ 1.000,00")).toBeInTheDocument(); });
  it("envia ciclos calculados, Bearer token e não envia valor_premio", async () => { await autenticarPelaSessao(); vi.mocked(fetch).mockResolvedValueOnce(resposta(grupoCriado(), 201)); fireEvent.click(screen.getByRole("button", { name: "+ Criar novo grupo" })); preencherGrupo(); fireEvent.click(screen.getByRole("button", { name: "Criar grupo" })); await screen.findByRole("status"); const payload = { nome: "Grupo dos Amigos", valor_cota: "200.00", quantidade_participantes: 10, quantidade_ciclos: 10, data_inicio: "2026-10-01" }; expect(payload).not.toHaveProperty("valor_premio"); expect(fetch).toHaveBeenLastCalledWith("http://127.0.0.1:8000/groups", expect.objectContaining({ method: "POST", headers: expect.objectContaining({ Authorization: "Bearer token-valido" }), body: JSON.stringify(payload) })); });
  it("mostra confirmação e o prêmio retornado pela API", async () => { await autenticarPelaSessao(); vi.mocked(fetch).mockResolvedValueOnce(resposta(grupoCriado(), 201)); fireEvent.click(screen.getByRole("button", { name: "+ Criar novo grupo" })); preencherGrupo(); fireEvent.click(screen.getByRole("button", { name: "Criar grupo" })); expect(await screen.findByText("Grupo criado com sucesso.")).toBeInTheDocument(); expect(screen.getByRole("heading", { name: "Grupo dos Amigos" })).toBeInTheDocument(); expect(screen.getByText("Valor do prêmio")).toBeInTheDocument(); expect(screen.getByText("R$ 2.000,00")).toBeInTheDocument(); expect(screen.getByText("01/10/2026")).toBeInTheDocument(); });
  it("não envia formulário com campos obrigatórios vazios", async () => { await autenticarPelaSessao(); fireEvent.click(screen.getByRole("button", { name: "+ Criar novo grupo" })); fireEvent.click(screen.getByRole("button", { name: "Criar grupo" })); expect(fetch).toHaveBeenCalledTimes(1); });
  it("mostra mensagem simples para erro de validação da API", async () => { await autenticarPelaSessao(); vi.mocked(fetch).mockResolvedValueOnce(resposta({ detail: [{ msg: "Value error" }] }, 422)); fireEvent.click(screen.getByRole("button", { name: "+ Criar novo grupo" })); preencherGrupo(); fireEvent.click(screen.getByRole("button", { name: "Criar grupo" })); expect(await screen.findByRole("alert")).toHaveTextContent("Confira os dados do grupo e tente novamente."); });
  it("mostra mensagem da API quando a criação falha", async () => { await autenticarPelaSessao(); vi.mocked(fetch).mockResolvedValueOnce(resposta({ detail: "Não foi possível criar o grupo agora." }, 500)); fireEvent.click(screen.getByRole("button", { name: "+ Criar novo grupo" })); preencherGrupo(); fireEvent.click(screen.getByRole("button", { name: "Criar grupo" })); expect(await screen.findByRole("alert")).toHaveTextContent("Não foi possível criar o grupo agora."); expect(screen.getByRole("heading", { name: "Criar grupo" })).toBeInTheDocument(); });
});
